name: 'AwsDestroy'

on:  
  workflow_dispatch:
    inputs:
      environment:
        type: string
        required: true

env:
  aws-bucket-prefix: ${{ vars.BUCKET_PREFIX }}
  aws-admin-role: ${{ secrets[format('{0}_AWS_ADMIN_ROLE', inputs.environment)] }}
  aws-github-role: ${{ secrets[format('{0}_AWS_GITHUB_ROLE', inputs.environment)] }}
  aws-main-role: ${{ secrets[format('{0}_AWS_MASTER_ROLE', inputs.environment)] }}
  aws-region: ${{ vars[format('{0}_AWS_REGION', inputs.environment)] }}
  initiative: ${{ vars.INITIATIVE }}
  shared-client-id: ${{ secrets.SHARED_CLIENT_ID }}
  shared-secret: ${{ secrets.SHARED_SECRET }}

permissions:
  contents: read
  id-token: write

jobs:
  
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
    - id: checkout
      name: checkout
      uses: actions/checkout@v7
      
    - name: "Terraform Destroy"
      uses: cailleach-mudengine/mudengine-infra/.github/actions/tf/tf-destroy@feature/refactor
      with:
        aws-bucket-prefix: ${{ env.aws-bucket-prefix }}
        aws-admin-role: ${{ env.aws-admin-role }}
        aws-github-role: ${{ env.aws-github-role }}
        aws-main-role: ${{ env.aws-main-role }}
        aws-region: ${{ env.aws-region }}
        shared-client-id: ${{ env.shared-client-id }}
        shared-secret: ${{ env.shared-secret }}
        is-infra-script: true
        initiative: ${{ env.initiative }}        
        environment: ${{ inputs.environment }}
        message: "GitHub Push in Main Branch"