name: 'AwsPullRequest'

on:  
  workflow_call:
    inputs:
      initiative:
        type: string
        required: true
      environment:
        type: string
        required: true
      service-name:
        type: string
        required: false
      revision:
        type: string
        required: false
      git-organization:
        type: string
        required: true
      aws-bucket-prefix:
        type: string
        required: true    
      aws-region:
        type: string
        required: true
        description: Region where to run Terraform script
    secrets:
      shared-client-id:
        type: string
        required: true
      shared-secret:
        type: string
        required: true
      aws-github-role:
        type: string
        required: true
        description: Role to be used to run Terraform script
      aws-main-role:
        type: string
        required: true
        description: Role to be used to run Terraform script
      aws-admin-role:
        type: string
        required: true
        description: Additional role to access AWS Core Account        

jobs:

  terraform-plan:
    runs-on: ubuntu-latest

    steps:
    - id: checkout
      name: checkout
      uses: actions/checkout@v7
      
    - id: plan
      name: Terraform Plan
      uses: cailleach-devops/aws-shared-actions/.github/actions/tf/tf-plan@tf-actions
      with:
        aws-bucket-prefix: ${{ inputs.aws-bucket-prefix }}
        aws-admin-role: ${{ inputs.aws-admin-role }}
        aws-github-role: ${{ inputs.aws-github-role }}
        aws-main-role: ${{ inputs.aws-main-role }}
        aws-region: ${{ inputs.aws-region }}
        shared-client-id: ${{ inputs.shared-client-id }}
        shared-secret: ${{ inputs.shared-secret }}
        is-infra-script: true
        initiative: ${{ inputs.initiative }}
        environment: ${{ inputs.environment }}
        git-organization: ${{ inputs.git-organization }}
        