name: 'OnDestroy'

on:  
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  starter-ecs-dev-publish:
    uses: cailleach-mudengine/mudengine-infra/.github/workflows/aws-ecs-destroy.yml@feature/refactor
    with:
      environment: "dev"
    secrets: inherit
