name: 'OnDestroy'

on:  
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  starter-ecs-dev-publish:
    uses: cailleach-devops/aws-shared-actions/.github/workflows/aws-ecs-destroy.yml@main
    with:
      environment: 'dev'
      initiative: ${{ vars.INITIATIVE }}
      aws_bucket_prefix: ${{ vars.BUCKET_PREFIX }}
      aws_region: ${{ vars.DEV_AWS_REGION }}
      git_organization: ${{ github.repository_owner }}
    secrets:
      aws_admin_role: ${{ secrets.DEV_AWS_ADMIN_ROLE }}
      aws_github_role: ${{ secrets.DEV_AWS_GITHUB_ROLE }}
      aws_main_role: ${{ secrets.DEV_AWS_MASTER_ROLE }}
      shared_client_id: ${{ secrets.SHARED_CLIENT_ID }}
      shared_secret: ${{ secrets.SHARED_SECRET }}
