name: 'OnPullRequest'

on:  
  pull_request:
    types: [opened, reopened]
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write

env:
  environment: 'dev'  

jobs:
  starter-ecs-pull-request:
    uses: cailleach-mudengine/mudengine-infra/.github/workflows/aws-ecs-pull-request.yml@main
    with:
      environment: ${{ env.environment }}
      initiative: ${{ vars.INITIATIVE }}
      aws-bucket-prefix: ${{ vars.BUCKET_PREFIX }}
      aws-region: ${{ vars[format('{0}_AWS_REGION', env.environment)] }}
    secrets:
      aws-admin-role: ${{ secrets[format('{0}_AWS_ADMIN_ROLE', env.environment)] }}
      aws-github-role: ${{ secrets[format('{0}_AWS_GITHUB_ROLE', env.environment)] }}
      aws-main-role: ${{ secrets[format('{0}_AWS_MASTER_ROLE', env.environment)] }}
      shared-client-id: ${{ secrets.SHARED_CLIENT_ID }}
      shared-secret: ${{ secrets.SHARED_SECRET }}      
