name: 'OnPullRequest'

on:  
  pull_request:
    types: [opened, reopened]
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  starter-ecs-pull-request:
    uses: cailleach-devops/aws-shared-actions/.github/workflows/aws-ecs-pull-request.yml@main
    with:
      environment: 'dev'
      initiative: ${{ vars.INITIATIVE }}
      aws_bucket_prefix: ${{ vars.BUCKET_PREFIX }}
      aws_region: ${{ vars.DEV_AWS_REGION }}
      git_organization: ${{ github.repository_owner }}
    secrets:
      aws_admin_role: ${{ secrets.DEV_AWS_ADMIN_ROLE }}
      aws_github_role: ${{ secrets.DEV_AWS_GITHUB_ROLE }}
      aws_main_role: ${{ secrets.DEV_AWS_MASTER_ROLE }}
      shared_client_id: ${{ secrets.SHARED_CLIENT_ID }}
      shared_secret: ${{ secrets.SHARED_SECRET }}
