name: 'OnPushMain'

on:  
  workflow_dispatch:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  id-token: write

jobs:
  starter-ecs-dev-publish:
    uses: cailleach-mudengine/mudengine-infra/.github/workflows/aws-ecs-deploy.yml@test/pr
    with:
      environment: 'dev'
      initiative: ${{ vars.INITIATIVE }}
      aws-bucket-prefix: ${{ vars.BUCKET_PREFIX }}
      aws-region: ${{ vars[format('{0}_AWS_REGION', inputs.environment)] }}
    secrets:
      aws-admin-role: ${{ secrets[format('{0}_AWS_ADMIN_ROLE', inputs.environment)] }}
      aws-github-role: ${{ secrets[format('{0}_AWS_GITHUB_ROLE', inputs.environment)] }}
      aws-main-role: ${{ secrets[format('{0}_AWS_MASTER_ROLE', inputs.environment)] }}
      shared-client-id: ${{ secrets.SHARED_CLIENT_ID }}
      shared-secret: ${{ secrets.SHARED_SECRET }}      
