name: 'Terraform Local Prepare'
description: "Prepare a Terraform Local Execution"
inputs:
  initiative:
    required: true
  environment:
    required: true
  service-name:
    required: true
  revision:
    required: true
  git-organization:
    required: true
  aws-bucket-prefix:
    required: true
  aws-region:
    required: true
    description: Region where to run Terraform script
  fs-shared-username:
    required: true
  fs-shared-token:
    required: true
  aws-main-role:
    required: true
    description: Role to be used to run Terraform script
  aws-core-role:
    required: true
    description: Additional role to access AWS Core Account

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Get OIDC Token      
      id: get_oidc_token
      shell: bash
      run: |
        curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value' > /tmp/web_identity_token_file


    - name: Create Credentials file
      shell: bash
      env:
        AWS_CORE_ROLE: ${{ inputs.aws-core-role }}      
        AWS_REGION: ${{ inputs.aws-region }}
      run: |
        cat << 'EOF' > credentials.aws
        
        
        [core]
        region=${{ env.AWS_REGION }}
        role_arn=${{ env.AWS_CORE_ROLE }}
        web_identity_token_file=/tmp/web_identity_token_file
        role_session_name=coreSession
        
        EOF
        
        mkdir -p ~/.aws
        mv credentials.aws ~/.aws/credentials
        touch ~/.aws/config
      
      
    - name: Setup Terraform with specified version on the runner
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.11.3
        
    - name: Install Jinja2
      shell: bash
      run: pip install jinja2-cli
        
    - name: Create providers file
      shell: bash
      working-directory: ./terraform
      env:
        AWS_REGION: ${{ inputs.aws-region }}
        AWS_MAIN_ROLE: ${{ inputs.aws-main-role }}
        AWS_CORE_ROLE: ${{ inputs.aws-core-role }}
        STATE_BUCKET: "${{ inputs.aws-bucket-prefix}}-${{ inputs.initiative }}-terraform-state"
        STATE_KEY: "app/${{ inputs.service-name}}/terraform.tfstate"      
      run: | 
        jinja2 providers.jinja --strict \
          -D region="$AWS_REGION" \
          -D main_role="$AWS_MAIN_ROLE" \
          -D state_bucket="$STATE_BUCKET" \
          -D state_key="$STATE_KEY" \
          -D profile="core" \
        > providers.tf

      
    - name: Generate TFvar
      shell: bash
      working-directory: ./terraform
      run: | 
        cat << 'EOF' > .auto.tfvars
          business_unit_name="${{ inputs.business-unit-name }}"
          platform="${{ inputs.platform }}"
          deployment_key="${{ inputs.deployment_key }}"
          environment="${{ inputs.environment }}"
          bucket_prefix="${{ inputs.aws-bucket-prefix}}"
          git-organization="${{ inputs.git-organization }}"
          service_name="${{ inputs.service-name}}"
          revision="${{ inputs.revision }}"
        EOF
   
    - name: Terraform init
      id: init
      shell: bash
      working-directory: ./terraform
      run: | 
        git config --global url."https://${{ inputs.fs-shared-username }}:${{ inputs.fs-shared-token }}@github.com".insteadOf "https://github.com"
        git config --global advice.detachedHead false
        
        terraform init
